server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: laravel
    static_configs:
      - targets:
          - localhost
        labels:
          job: laravel
          __path__: /var/log/laravel/*.log
    pipeline_stages:
      - multiline:
          firstline: '^[\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^[(?P<timestamp>[^]]+)] (?P<channel>w+).(?P<level>w+): (?P<message>.*)'
      - labels:
          channel:
          level:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000Z"
          fallback_formats:
            - "2006-01-02 15:04:05"
